apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-pv-claim
  labels:
    app: jupyter-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-gp2-retain

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyterlab-pv-volume
  labels:
    type: local
    app: jupyterlab
spec:
  storageClassName: standard-gp2-retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jupyter"