
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    db: mongodb # this label needs to match workload resource label
  ports:
  - port: 27017 
    targetPort: mongodb-port