apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  selector:
    frontend: pgadmin
  ports:
  - name: pgadmin-port
    port: 80
    targetPort: pgadmin-port