apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  serviceName: nifi-headless
  replicas: 1
  selector:
    matchLabels:
      app: nifi

  template:
    metadata:
      annotations: {}
      labels:
        app: nifi
  
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: server
        imagePullPolicy: "IfNotPresent"
        image: "apache/nifi:1.23.2"
        command:
        - bash
        - -ce
        - |
          cp -a /opt/nifi/temp/. /opt/nifi/nifi-current/conf && exec /opt/nifi/nifi-current/bin/nifi.sh run
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 6007
          name: cluster
          protocol: TCP
        - containerPort: 7001
          name: processor01
          protocol: TCP
        - containerPort: 7002
          name: processor02
          protocol: TCP
        volumeMounts:
          - mountPath: /opt/nifi/temp
            name: nifi-properties
          - mountPath: /opt/nifi/nifi-current/logs
            name: data
            subPath: logs
          - mountPath: /opt/nifi/data
            name: data
            subPath: data
          - mountPath: /opt/nifi/nifi-current/auth-conf/
            name: data
            subPath: auth-conf
          - mountPath: /opt/nifi/nifi-current/config-data
            name: data
            subPath: config-data
          - mountPath: /opt/nifi/flowfile_repository
            name: data
            subPath: flowfile-repository
          - mountPath: /opt/nifi/content_repository
            name: data
            subPath: content-repository
          - mountPath: /opt/nifi/provenance_repository
            name: data
            subPath: provenance-repository
      volumes:
      - name: "nifi-properties"
        configMap:
          name: nifi-config
          items:
            - key: "nifi.properties"
              path: "nifi.properties"
      - name: data
        persistentVolumeClaim:
          claimName: nifi-pvc 
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       storageClassName: manual
  #       accessModes:
  #         - "ReadWriteOnce"
  #       resources:
  #         requests:
  #           storage: 8Gi

