apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  serviceName: nifi-headless
  replicas: 1
  selector:
    matchLabels:
      app: nifi

  template:
    metadata:
      annotations: {}
      labels:
        app: nifi
  
    spec:
      nodeName: goblincoln.com
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: server
        imagePullPolicy: "IfNotPresent"
        image: "apache/nifi:1.23.2"
        command:
        - bash
        - -ce
        - |
          cp -a /opt/nifi/temp/. /opt/nifi/nifi-current/conf
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 6007
          name: cluster
          protocol: TCP
        - containerPort: 7001
          name: processor01
          protocol: TCP
        - containerPort: 7002
          name: processor02
          protocol: TCP
        volumeMounts:
          - mountPath: /opt/nifi/nifi-current/logs
            name: data
            subPath: logs
          - mountPath: /opt/nifi/data
            name: data
            subPath: data
          - mountPath: /opt/nifi/nifi-current/auth-conf/
            name: data
            subPath: auth-conf
          - mountPath: /opt/nifi/nifi-current/config-data
            name: data
            subPath: config-data
          - mountPath: /opt/nifi/flowfile_repository
            name: data
            subPath: flowfile-repository
          - mountPath: /opt/nifi/content_repository
            name: data
            subPath: content-repository
          - mountPath: /opt/nifi/provenance_repository
            name: data
            subPath: provenance-repository
          - name: "bootstrap-conf"
            mountPath: /opt/nifi/nifi-current/conf/bootstrap.conf
            subPath: "bootstrap.conf"
          - name: "nifi-properties"
            mountPath: /opt/nifi/nifi-current/conf/nifi.temp
            subPath: "nifi.temp"
          - name: "authorizers-temp"
            mountPath: /opt/nifi/nifi-current/conf/authorizers.temp
            subPath: "authorizers.temp"
          - name: "bootstrap-notification-services-xml"
            mountPath: /opt/nifi/nifi-current/conf/bootstrap-notification-services.xml
            subPath: "bootstrap-notification-services.xml"
          - name: "login-identity-providers-ldap-xml"
            mountPath: /opt/nifi/nifi-current/conf/login-identity-providers-ldap.xml
            subPath: "login-identity-providers-ldap.xml"
          - name: "state-management-xml"
            mountPath: /opt/nifi/nifi-current/conf/state-management.xml
            subPath: "state-management.xml"
          - name: "zookeeper-properties"
            mountPath: /opt/nifi/nifi-current/conf/zookeeper.properties
            subPath: "zookeeper.properties"
          - name: "flow-content"
            mountPath: /opt/nifi/data/flow.xml
            subPath: "flow.xml"
      volumes:
      - name: "nifi-properties"
        configMap:
          name: nifi-config
          items:
            - key: "nifi.properties"
              path: "nifi.temp"
      - name: data
        persistentVolumeClaim:
          claimName: nifi-pvc 
  # volumeClaimTemplates:
  #   - metadata:
  #       name: data
  #     spec:
  #       storageClassName: manual
  #       accessModes:
  #         - "ReadWriteOnce"
  #       resources:
  #         requests:
  #           storage: 8Gi

