apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
type: Opaque 
data:
  postgres-user: {{ .Values.postgres.defaultUser | b64enc }}
  postgres-password: {{ .Values.postgres.defaultPassword | b64enc }}