apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-pvc
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.postgres.storageClass }}
  accessModes:
  - {{ .Values.postgres.storageAccessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageRequestSize }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . }}-pv
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.storageCapacity }}
  accessModes:
  - {{ .Values.postgres.storageAccessMode }}
  hostPath:
    path: /mnt/postgres-training
