apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.postgres.servicePort }}
    name: postgres-port
    targetPort: postgres-port
