apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
type: Opaque 
data:
  postgres-user: YWRtaW4= # base64 of 'admin'
  postgres-password: YWRtaW4= # base64 of 'admin'