apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    db: postgres
  ports:
  - port: 5432
    targetPort: postgres-port
