apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      frontend: pgadmin
  template:
    metadata:
      labels:
        frontend: pgadmin
    spec:
      securityContext:
        fsGroup: #
      containers:
      - name: pgadmin
        image: #
        imagePullPolicy: IfNotPresent
        ports:
        - name: #
          containerPort: 80
        env: 
        - name: PGADMIN_DEFAULT_EMAIL
          value: #
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #
              key: #

# The following is found here: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
# Warning: pgAdmin runs as the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050) in the container. You must ensure that all files are readable, and where necessary (e.g. the working/session directory) writeable for this user on the host machine. For example:
# sudo chown -R 5050:5050 <host_directory>