pgadmin:

  # image configuration
  image: dpage/pgadmin4:8.14.0
  imagePullPolicy: IfNotPresent

  # network configuration
  containerPort: 80
  servicePort: 80

  # default credentials
  defaultEmail: "admin@email.com"
  defaultPassword: admin