apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-deployment
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_BASICAUTH
              value: "false"
            - name: ME_CONFIG_MONGODB_URL
              valueFrom: 
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-url