apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
spec:
  tls:
  - hosts:
      - nifi.k8s.com
    secretName: dev-ingress-tls
  rules:
    - host: mongo.k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongodb-express-service
                port:
                  number: 8081
    - host: pgadmin.k8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80
    - host: nifi.k8s.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nifi-service
              port:
                number: 8443
    - host: jupyterlab.k8s.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jupyterlab-service
              port:
                number: 8888
