apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{ include "pgadmin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 5050
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.pgadmin.image }}
        imagePullPolicy: {{ .Values.pgadmin.imagePullPolicy }}
        ports:
        - name: pgadmin
          containerPort: 80
        env: 
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin.defaultEmail }}
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "pgadmin.fullname" . }}-secret
              key: default-password
